#!/bin/sh
#
# This script run the tests of an sbt project and commit only if tests are passing

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
	else
		# Initial commit: diff against an empty tree object
			against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

# Redirect output to stderr.
exec 1>&2

activator test
if [ $? -eq 0 ]; then
	echo "\n [git] Tests have passed, changes commited!\n"
	exit 0
else
	echo "\n [git] Tests have failed, aborting commit!\n"
	exit 1
fi
